name: Release Plugins

on:
  push:
    branches:
      - master
      - main
    # tags:
    #   - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'wiki/**'
      - 'public/**'
      - 'scripts/**'
      - '.vscode'
      - '.idea'
  pull_request:
    branches:
      - master
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'wiki/**'
      - 'public/**'
      - '.scripts/**'
      - '.vscode'
      - '.idea'

concurrency:
  group: release-ci-group
  cancel-in-progress: true

jobs:
  Plugins:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Plugins
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
